import type { Metadata } from 'next'
import { Geist, Geist_Mono } from 'next/font/google'
import '../globals.css'
import { currentUser } from '@clerk/nextjs/server'
import { db } from '@/db'
import Servers from '@/components/Servers'
import { UserButton } from '@clerk/nextjs'

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin']
})

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin']
})

export const metadata: Metadata = {
  title: 'Discord Clone',
  description: 'Generated by create next app'
}

export default async function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode
}>) {
  await db.$connect()
  const user = await currentUser()
  const realUser = user
    ? await db.user.findUnique({
        where: {
          clerk_id: user.id
        }
      })
    : null
  await db.$disconnect()
  return (
    <div className={`w-full h-full flex flex-row ${geistSans.variable} ${geistMono.variable} antialiased`} >
      <Servers user={realUser!} />
      <div
        id='sidebar-channels'
        className='bg-[#2b2d31] w-[400px] h-full'
      >
        <div className='w-full h-[94%] bg-inherit'>
          dms
        </div>
        <div className='w-full h-[6%] bg-[#232428] flex items-center p-3 relative flex-row gap-x-2'>
          <UserButton />
          <div className='flex flex-col gap-y-0'>
            <span className='text-slate-300'>{realUser?.username}</span>
            <span>tag</span>
          </div>
        </div>
      </div>
      <div
        id='main'
        className='bg-[#313338] w-full h-full'
      >
        {children}
      </div>
    </div>
  )
}
