import type { Metadata } from 'next'
import { Geist, Geist_Mono } from 'next/font/google'
import '../globals.css'

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
})

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
})

export const metadata: Metadata = {
  title: 'Tjorss | Signin',
  description: 'Generated by create next app',
}

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <div className='w-full h-full flex justify-center bg-white p-48'>
      <div id="signincard" className='rounded-lg w-[600px] h-fit border-2 border-black/80 text-black p-8 flex flex-col items-center'>
        {children}
      </div>
    </div>
  )
}
