import type { Metadata } from 'next'
import { Toaster } from 'react-hot-toast'
import { Geist, Geist_Mono } from 'next/font/google'
import '../globals.css'
import Navbar from '@/components/Navbar'

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin']
})

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin']
})

export const metadata: Metadata = {
  title: 'Discord Clone | Signin',
  description: 'Generated by create next app'
}

export default async function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <div className='flex flex-col w-full h-full'>
      <Navbar />
      <div className='w-full h-full flex justify-center bg-black p-24'>
        <div
          id='signincard'
          className='rounded-lg w-[600px] h-full border-2 border-white/80 text-white p-8 flex flex-col items-center'
        >
          {children}
        </div>
        <Toaster />
      </div>
    </div>
  )
}
