import type { Metadata } from 'next'
import { Geist, Geist_Mono, Atkinson_Hyperlegible } from 'next/font/google'
import { Toaster } from 'react-hot-toast'
import Providers from './providers'
import './globals.css'

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin']
})

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin']
})

const atkinson = Atkinson_Hyperlegible({
  variable: '--font-atkinson',
  subsets: ['latin'],
  weight: '400'
})

export const metadata: Metadata = {
  title: 'Discord Clone',
  description: 'Generated by create next app'
}

export default async function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html
      lang='en'
      className='w-full h-full'
    >
      <body className={`${atkinson.className} antialiased w-full h-full`}>
        <Providers>{children}</Providers>
        <Toaster />
      </body>
    </html>
  )
}
