import type { Metadata } from 'next'
import { Geist, Geist_Mono } from 'next/font/google'
import '../../globals.css'
import Servers from '@/components/Servers'
import SidebarTopAndMain from '@/components/SidebarAndMain'
import { createClient } from '@/utils/supabase/server'
import { Tables } from '@/database.types'

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin']
})

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin']
})

export const metadata: Metadata = {
  title: 'Discord Clone',
  description: 'Generated by create next app'
}

export default async function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode
}>) {
  const supabase = await createClient()
  const user = await supabase.auth.getUser()

  const dbUser = user.data.user?.id
    ? await supabase
        .from('users')
        .select('*')
        .eq('token', user.data.user.id)
        .single()
    : null
  return (
    <div
      className={`w-full h-full flex flex-row ${geistSans.variable} ${geistMono.variable} antialiased`}
    >
      <Servers user={dbUser?.data as Tables<'users'>} />
      <SidebarTopAndMain>{children}</SidebarTopAndMain>
    </div>
  )
}
