import type { Metadata } from 'next'
import { Geist, Geist_Mono } from 'next/font/google'
import '../../globals.css'
import Servers from '@/components/Servers'
import SidebarTopAndMain from '@/components/SidebarAndMain'
import CurrentChannelContext from './context'
import { useUser } from '@clerk/nextjs'

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin']
})

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin']
})

export const metadata: Metadata = {
  title: 'Discord Clone',
  description: 'Generated by create next app'
}

export default async function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode
}>) {
  const user = useUser();
  
  
  // #1d1e21
  return (
    <CurrentChannelContext>
      <div className={`w-full h-full flex flex-row ${geistSans.variable} ${geistMono.variable} antialiased`}>
        <Servers user={dbUser!} />
        <SidebarTopAndMain>
          {children}
        </SidebarTopAndMain>
      </div>
    </CurrentChannelContext>
  )
}
