import type { Metadata } from 'next'
import { Geist, Geist_Mono } from 'next/font/google'

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
})

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
})

export const metadata: Metadata = {
  title: 'Discord Clone | Signin',
  description: 'Generated by create next app',
}

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <div className='w-full h-full flex items-center justify-center bg-black pt-20 pb-20'>
      <div id="signincard" className='rounded-lg w-64 h-fit border-2 border-white/80'>
        {children}
      </div>
    </div>
  )
}