import type { Metadata } from 'next'
import { Geist, Geist_Mono } from 'next/font/google'

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
})

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
})

export const metadata: Metadata = {
  title: 'Discord Clone | Signin',
  description: 'Generated by create next app',
}

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <div className='w-full h-full flex items-center justify-center bg-white'>
      <div id="signincard" className='rounded-lg shadow-sm shadow-slate-700 w-64 h-64 border-2 border-black'>
        {children}
      </div>
    </div>
  )
}